name: virtual_toy_shop
description: Flutter Virtual Shop project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.2.1+8

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1

  #localization
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0


  #view
  mask_text_input_formatter: ^2.3.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4
  android_intent_plus: ^3.1.1
  page_transition: ^2.0.5
  #audioplayers: ^1.0.1
  soundpool: ^2.4.1  # Update to the latest version
  video_player: ^2.4.7
  flutter_slidable: ^3.1.0
  card_swiper: ^3.0.1
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  gradient_borders: ^0.2.0
  cached_network_image: ^3.3.0


  #logic
  get_it: ^7.2.0
  device_info_plus: ^3.2.4

  #rest
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1


  #storage
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.2.0

  #config
  flutter_launcher_icons: ^0.9.3
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: VAG Rounded Std
      fonts:
        - asset: fonts/VAG Rounded Std Bold.otf
          weight: 900
